CC = gcc
CFLAGS = -g -std=gnu99 -Wno-implicit-function-declaration
LDFLAGS = -L../src/obj -lcgds
INCLUDES = -I.. -I../src
TARGET = testcgds

all: obj/$(TARGET)

clean:
	rm -f obj/*.o
	rm -f obj/$(TARGET)

.PHONY: all clean
